name: Arduino Lint

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
    - hotfix/*
  workflow_dispatch:

jobs:
  lint:
    name: Arduino Lint
    runs-on: ubuntu-latest

    steps:
    - name: arduino/arduino-lint-action
      uses: arduino/arduino-lint-action@v1.0.2
